In [1]:
import pandas as pd
import os
from typing import List, Optional

In [3]:
#Specify Excel file path
attendance_v3_file_path = "../../data/Attendance_Template_v3.xlsx"
#Load in Excel file
attendance_v3_file = pd.ExcelFile(attendance_v3_file_path)
#Iterate through each sheet in Excel file
for sheet_name in attendance_v3_file.sheet_names:
    #Read in the current sheet
    mentor_df = pd.read_excel(attendance_v3_file_path, sheet_name=sheet_name)
    #Using the sheet name, define the CSV output file
    csv_output_file = f"../../data/{sheet_name}.csv"
    #Save the df to CSV
    mentor_df.to_csv(csv_output_file, index=False)

In [4]:
#Reading in MeetCodes file
MeetCodes = pd.read_csv("../../data/MeetCodes.csv")
#Reading in class attendance reports as excel files
Attendance_Report_07302025 = pd.read_excel("../../data/2025-07-29 17_45 wrt-nsga-feo Attendance Report.xlsx")
Attendance_Report_07292025 = pd.read_excel("../../data/2025-07-30 17_50 kan-ptwt-ehz Attendance Report.xlsx")

In [5]:
# Reading in class attendance reports to csv 

Attendance_Report_07302025.to_csv("../../data/DataJan25_wrt-nsga-feo_07292025.csv", index = None, header = True)
Attendance_Report_07292025.to_csv("../../data/WebJan25_kan-ptwt-ehz_07302025.csv",index = None, header = True)

In [6]:
# Creating attendance reports dataframes
Data_Jan_25_07292025 = pd.read_csv("../../data/DataJan25_wrt-nsga-feo_07292025.csv")
Web_Jan_25_07302025 = pd.read_csv("../../data/WebJan25_kan-ptwt-ehz_07302025.csv")

In [18]:
#view attendance dataframes
attendance = [Data_Jan_25_07292025, Web_Jan_25_07302025]
for a in attendance:
    display(a.head())

,First name,Last name,Email,Duration,Time joined,Time exited
0,Alex,D,awda*****@***.com,2 hr 25 min,6:01 PM,8:26 PM
1,Angela,Moore,ange*************@***.com,2 hr 29 min,5:59 PM,8:27 PM
2,Bill,Montgomery,kyho***@***.com,2 hr 27 min,5:59 PM,8:26 PM
3,Charles,Norman,ario****@***.com,2 hr 42 min,5:45 PM,8:27 PM
4,Christina,Porter,chri**************@***.com,2 hr 4 min,6:15 PM,8:19 PM

,First name,Last name,Email,Duration,Time joined,Time exited
0,Sheyla,Diaz,dshe*****@***.com,1 hr 43 min,5:58 PM,7:41 PM
1,James,Glosser,demo**********@***.com,1 hr 40 min,6:01 PM,7:41 PM
2,Reed,Haddix,shir***********@***.com,1 hr 46 min,5:55 PM,7:41 PM
3,John,Hankins,john**********@***.com,1 hr 38 min,6:03 PM,7:41 PM
4,Stephanie,Jones,step*******************@***.com,1 hr 48 min,5:53 PM,7:41 PM

In [22]:
# Add columns for Meet Code & Date
Data_Jan_25_07292025["Meet Code"] = "wrt-nsga-feo"
Data_Jan_25_07292025["Date"] = "07/29/2025"
Web_Jan_25_07302025["Meet Code"] = "kan-ptwt-ehz"
Web_Jan_25_07302025["Date"] = "07/30/2025"

attendance = [Data_Jan_25_07292025, Web_Jan_25_07302025]
for a in attendance:
    display(a.head())

,First name,Last name,Email,Duration,Time joined,Time exited,Meet Code,Date
0,Alex,D,awda*****@***.com,2 hr 25 min,6:01 PM,8:26 PM,wrt-nsga-feo,07/29/2025
1,Angela,Moore,ange*************@***.com,2 hr 29 min,5:59 PM,8:27 PM,wrt-nsga-feo,07/29/2025
2,Bill,Montgomery,kyho***@***.com,2 hr 27 min,5:59 PM,8:26 PM,wrt-nsga-feo,07/29/2025
3,Charles,Norman,ario****@***.com,2 hr 42 min,5:45 PM,8:27 PM,wrt-nsga-feo,07/29/2025
4,Christina,Porter,chri**************@***.com,2 hr 4 min,6:15 PM,8:19 PM,wrt-nsga-feo,07/29/2025

,First name,Last name,Email,Duration,Time joined,Time exited,Meet Code,Date
0,Sheyla,Diaz,dshe*****@***.com,1 hr 43 min,5:58 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
1,James,Glosser,demo**********@***.com,1 hr 40 min,6:01 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
2,Reed,Haddix,shir***********@***.com,1 hr 46 min,5:55 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
3,John,Hankins,john**********@***.com,1 hr 38 min,6:03 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
4,Stephanie,Jones,step*******************@***.com,1 hr 48 min,5:53 PM,7:41 PM,kan-ptwt-ehz,07/30/2025

In [27]:
# Combine the data 
Students = pd.concat([Data_Jan_25_07292025, Web_Jan_25_07302025], axis = 0)
# Write df to individual CSV
Students.to_csv("../../data/Students.csv", index = None, header = True)

display(Students.head())

,First name,Last name,Email,Duration,Time joined,Time exited,Meet Code,Date
0,Alex,D,awda*****@***.com,2 hr 25 min,6:01 PM,8:26 PM,wrt-nsga-feo,07/29/2025
1,Angela,Moore,ange*************@***.com,2 hr 29 min,5:59 PM,8:27 PM,wrt-nsga-feo,07/29/2025
2,Bill,Montgomery,kyho***@***.com,2 hr 27 min,5:59 PM,8:26 PM,wrt-nsga-feo,07/29/2025
3,Charles,Norman,ario****@***.com,2 hr 42 min,5:45 PM,8:27 PM,wrt-nsga-feo,07/29/2025
4,Christina,Porter,chri**************@***.com,2 hr 4 min,6:15 PM,8:19 PM,wrt-nsga-feo,07/29/2025

In [33]:
# Change column headers to string
Students.columns = [str(col) for col in Students.columns]

# Capatalize each individual word in column header
Students.columns = Students.columns.str.title()

display(Students)

,First Name,Last Name,Email,Duration,Time Joined,Time Exited,Meet Code,Date
0,Alex,D,awda*****@***.com,2 hr 25 min,6:01 PM,8:26 PM,wrt-nsga-feo,07/29/2025
1,Angela,Moore,ange*************@***.com,2 hr 29 min,5:59 PM,8:27 PM,wrt-nsga-feo,07/29/2025
2,Bill,Montgomery,kyho***@***.com,2 hr 27 min,5:59 PM,8:26 PM,wrt-nsga-feo,07/29/2025
3,Charles,Norman,ario****@***.com,2 hr 42 min,5:45 PM,8:27 PM,wrt-nsga-feo,07/29/2025
4,Christina,Porter,chri**************@***.com,2 hr 4 min,6:15 PM,8:19 PM,wrt-nsga-feo,07/29/2025
5,Cindy,Wedding,cwed*******@***.com,2 hr 22 min,6:03 PM,8:25 PM,wrt-nsga-feo,07/29/2025
6,Classroom,Admin,classroom@codeyou.org,1 min,5:59 PM,6:00 PM,wrt-nsga-feo,07/29/2025
7,Joel,Anderson,joel*************@***.com,2 hr 27 min,6:00 PM,8:27 PM,wrt-nsga-feo,07/29/2025
8,Jonathan,Chadwell,jona*******************@***.com,2 hr 24 min,6:02 PM,8:26 PM,wrt-nsga-feo,07/29/2025
9,Mendell,M,menm****@***.com,1 hr 58 min,6:00 PM,8:00 PM,wrt-nsga-feo,07/29/2025
10,Oli,Ivanova,olga************@***.com,2 hr 14 min,5:59 PM,8:13 PM,wrt-nsga-feo,07/29/2025
11,S.,Byrnes,smby***@***.com,1 hr 58 min,6:02 PM,8:00 PM,wrt-nsga-feo,07/29/2025
12,Tara Leigh,Hylton,turr******@***.com,2 hr 5 min,6:01 PM,8:06 PM,wrt-nsga-feo,07/29/2025
13,Whitney,Parks,wypa*****@***.com,2 hr 38 min,6:01 PM,8:39 PM,wrt-nsga-feo,07/29/2025
14,Zachary,Young,zach*************@***.com,2 hr 6 min,5:54 PM,8:00 PM,wrt-nsga-feo,07/29/2025
15,Zhenzhen,Xie,xzz.**********@***.com,2 hr 24 min,6:01 PM,8:26 PM,wrt-nsga-feo,07/29/2025
0,Sheyla,Diaz,dshe*****@***.com,1 hr 43 min,5:58 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
1,James,Glosser,demo**********@***.com,1 hr 40 min,6:01 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
2,Reed,Haddix,shir***********@***.com,1 hr 46 min,5:55 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
3,John,Hankins,john**********@***.com,1 hr 38 min,6:03 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
4,Stephanie,Jones,step*******************@***.com,1 hr 48 min,5:53 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
5,Aaron,LaLiberty,daei**@***.com,1 hr 39 min,6:02 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
6,Dakota,McMullin,kota****@***.com,1 hr 11 min,5:59 PM,7:11 PM,kan-ptwt-ehz,07/30/2025
7,Toni-Ivy,Ownn.,toni*********@***.com,1 hr 40 min,6:01 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
8,Michael,Puckett,mich***********@***.com,1 hr 37 min,6:04 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
9,Leighton,Pulliam,l8on**@***.com,1 hr 40 min,6:00 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
10,ken,quiggins,kash************@***.com,1 hr 43 min,5:58 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
11,Amber,Ratliff,arat********@***.com,1 hr 40 min,6:01 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
12,Jill,Schrank,just*******@***.com,1 hr 41 min,5:59 PM,7:41 PM,kan-ptwt-ehz,07/30/2025
13,Huan,Song,huan********@***.com,1 hr 43 min,5:58 PM,7:41 PM,kan-ptwt-ehz,07/30/2025